### PR TITLE
Bump version to 0.9.0

### LINKED ISSUE #2: No version available for Python >= 3.7
### Comment:

The current package is only available for Python <3.7: https://github.com/conda-forge/aiozmq-feedstock/blob/cef225cda15cfa2dc7b31a462e933bc83db75e64/recipe/meta.yaml#L24

New versions are available that are compatible. It would be nice to update this feedstock.

### PR DESCRIPTION
**Pull request by beenje**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Bump version to 0.9.0 and update dependencies:
- remove max python version
- do not use pyzmq 17.1.2

Fix #2

### CODE REVIEW

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
@cjw85 could you please review this?

**Comment by cjw85** [comment]
Other than saying lgtm I don't know that I can really comment as I'm not up to date with conda forge processes. I made this recipe a long time ago when trying to get something into bioconda and haven't needed to come back.

**Comment by beenje** [comment]
@conda-forge-admin, please rerender

**Comment by beenje** [comment]
All the checks are OK, so you just have to merge.
I added myself as maintainer as well, so I can help to keep this recipe up to date in the future if it's ok with you.

**Comment by beenje** [comment]
@cjw85 do you have the permission to merge this? I see you weren't automatically added as reviewer to this PR. Something might not be configured properly.
If that's not the case, we have to ask the core team.

**Pull request merged**
